name: elix-star-live
region: fra
static_sites:
- name: elix-star-live
  source_dir: /
  github:
    repo: bericaandrei1-arch/Elix-Star-Live-Good-MVP-Updated
    branch: main
  build_command: npm run build
  output_dir: dist
  routes:
  - path: /
  envs:
  - key: VITE_SUPABASE_URL
    value: ${VITE_SUPABASE_URL}
  - key: VITE_SUPABASE_ANON_KEY
    value: ${VITE_SUPABASE_ANON_KEY}
  - key: VITE_AGORA_APP_ID
    value: ${VITE_AGORA_APP_ID}
  - key: VITE_STRIPE_PUBLISHABLE_KEY
    value: ${VITE_STRIPE_PUBLISHABLE_KEY}
